### ISSUE TITLE
Restyle - Restyling delle card per le recycler view 

### ISSUE THREAD

**Issue by GaetanoCimino** [corso-android-ivan-morgillo/team-a#13]
Abbiamo bisogno di ristrutturare le card per una visualizzazione migliore delle informazioni. 

<img width="364" alt="Schermata 2021-02-07 alle 16 45 41" src="https://user-images.githubusercontent.com/64216397/107151653-f94a3180-6963-11eb-8066-e72b617f9a9e.png">

**Comment by L-Pace** [comment]
https://material.io/components/cards#card-collections

**Comment by L-Pace** [comment]
![image](https://user-images.githubusercontent.com/98166/107488453-481fe300-6b7f-11eb-968d-8323f7041e5f.png)

**Comment by L-Pace** [comment]
Il Main Menu' e' una serie di Cards su due colonne. Le cards sono una serie di categorie dove ci si puo' clickare e passare al layout successivo. Da decidere se la lista successiva e' su due colonne oppure su due colonne come il main Menu'.

**Comment by GaetanoCimino** [comment]
Behaviour della lista che conterrà le nostre cards.

https://material.io/components/image-lists#behavior

**Comment by Guaik4** [comment]
![image](https://user-images.githubusercontent.com/78148228/107500270-444b8b00-6b96-11eb-916e-66458ff105c2.png)

penso che si deva aggiungere il tasto note, il taso verra abilitato nel momento in cui l'utente aggiunge la ricetta nei preferiti e se la salva sul dispositivo. Le note sono solo visibili solo all'utente.

**Comment by GaetanoCimino** [comment]
Cose utili quando ci sono più card nella stessa schermata (come disposizione e simili) 

https://material.io/components/cards#card-collections

**Comment by GaetanoCimino** [comment]
Style possibile delle cards: 

![IMAGE 2021-02-10 12:09:15](https://user-images.githubusercontent.com/64216397/107502310-cb99fe00-6b98-11eb-9f4f-0aee7243e311.jpg)

**Comment by Enigmo96** [comment]
Tabs: https://www.geeksforgeeks.org/how-to-implement-tabs-viewpager-and-fragment-in-android-using-kotlin/
