### ISSUE TITLE
Possibilita' di  inserire note nella ricetta

### ISSUE THREAD

**Issue by Guaik4** [corso-android-ivan-morgillo/team-a#16]
Valutare se salvare la ricetta in locale

**Comment by Guaik4** [comment]
Parliamo di note personali che possono essere aggiunti solo alle ricette che troviamo tra i preferiti.

**Comment by GaetanoCimino** [comment]
Tipo review alle ricette?

**Comment by Guaik4** [comment]
Si, proprio una review delle ricette che sono tra i preferiti, in modo che ogni utente posso aggiungere delle note in caso in cui abbiano modificato un ingrediente ho una procedura di preparazione, in questo modo possono tenere traccia

**Comment by Guaik4** [comment]
ma nelle note dobbiamo mettere un correttore di testo oppure e' qualcosa che si fa automaticamente?
