### ISSUE TITLE
Gestione Stati di Errore

### ISSUE THREAD

**Issue by GaetanoCimino** [corso-android-ivan-morgillo/team-a#29]
Implementare la gestione degli errori scatenati dal No internet, Slow internet ecc....

**Comment by GaetanoCimino** [comment]
- Esempio no Internet : 

![photo_2021-02-10 09 44 39](https://user-images.githubusercontent.com/64216397/107485875-a7ccbd00-6b84-11eb-9b2f-146e3e3ea177.jpeg)
![photo_2021-02-10 09 44 40](https://user-images.githubusercontent.com/64216397/107485879-a8655380-6b84-11eb-89ea-eabcffdfc719.jpeg)

**Comment by GaetanoCimino** [comment]
Per Gli errori in cui l'utente deve fare qualcosa e deve "Risolversi il problema" come --> Accendi internet, possiamo mostrare dei dialogs chiari che spieghino all'utente cosa sta succedendo.

Se per esempio l'errore non dipende dall'utente --> Server Error, allora si può segnalare in un altro modo.

**Comment by L-Pace** [comment]
https://material.io/components/dialogs/android#alert-dialog

**Comment by L-Pace** [comment]
![image](https://user-images.githubusercontent.com/98166/107486749-50771e80-6b7d-11eb-81f4-d83ab837454c.png)
![image](https://user-images.githubusercontent.com/98166/107486796-5cfb7700-6b7d-11eb-950f-5786b5217105.png)

**Comment by GaetanoCimino** [comment]
Implementazione immagine nel dialogs android in vari modi. 

https://stackoverflow.com/questions/6276501/how-to-put-an-image-in-an-alertdialog-android

**Comment by L-Pace** [comment]
Gestire l'errore ConnectException che viene innescato quando stiamo scaricando la lista delle ricette dal server e perdiamo la connesisone prima di aver ricevuto la lista.
