### ISSUE TITLE
AlertDialog mostrato ogni volta che si verifica onResume() nella MainActivity

### ISSUE THREAD

**Issue by Enigmo96** [corso-android-ivan-morgillo/team-a#47]
Ho notato che l'evento OnReady viene generato dal viewModel ogni volta che si esegue la funzione onResume(), SE lo stato attuale è Loading. E di conseguenza viene mostrato sempre un nuovo AlertDialog sopra al precedente.

Per verificare, provare quanto segue:
Disconnettere il device da internet e aprire l'app. Verrà generato l'evento OnReady che a sua volta farà andare l'app nello stato Loading. Il caricamento fallirà perchè il device non è connesso a internet, mostrando quindi un AlertDialog di errore.
A questo punto, se non si clicca nulla e si mette l'app in background (ad esempio si va alla Home), e poi si ritorna nell'app, si nota come venga creato un nuovo AlertDialog sopra al precedente.
Per confermare quanto scritto sopra, basta ripetere l'esempio precedente ma connettendo il device a internet PRIMA di riaprire l'app dal background: si vede che la lista delle ricette viene caricata correttamente ma l'AlertDialog è ancora visibile.

Soluzione proposta: nella funzione onResume(), inviare l'evento OnReady solamente se lo stato attuale è null (cioè se l'app non ha mai caricato i dati dalla sua apertura)

**Comment by GaetanoCimino** [comment]
Onestamente ci sta, infatti ci sfugge qualcosa appunto nella or resume. 

Quello che non capisco è perchè dopo la onCreate viene eseguita subito anche la onResume anche se l'app è aperta per la prima volta?

Comunque sicuramente sarà un fix veramente piccolo che ci sfugge.

**Comment by Enigmo96** [comment]
Se guardi in una documentazione su internet del ciclo di vita, vedrai che è normale che venga eseguita la onResume() ogni volta dopo una onCreate(), quindi non c'è nessun bug in questo senso

**Comment by GaetanoCimino** [comment]
si ma Comunque è un pò strano che venga eseguita, nel senso... ok è giusto funziona così... ma il primo avvio è una create non un resume.. però ok :)

**Comment by GaetanoCimino** [comment]
L'unica cosa che posso dire con certezza dopo alcune prove è che: 

- Se l'activity starta senza internet, viene mostrato il popup e lo stato viewModel.states.value si trova a null sia in on create che in on resume (quindi primo avvio senza internet

- Se a questo punto si attacca internet senza andare nelle impostazioni seguendo il pulsante del Dialog, riaprendo l'app, lo stato viewModel.states.value cambia da solo in Loading. 

Sinceramente non ho capito perchè.

**Comment by Enigmo96** [comment]
Al primo avvio è null per definizione diciamo, nel senso che non c'è uno stato iniziale e quindi è null. Ma appena inizia il caricamento diventa Loading. Questo Loading poi viene interrotto dall'errore, e quindi rimane così qualunque cosa si faccia dopo. O almeno, io l'ho capita così
