### ISSUE TITLE
Gestire stato pausa del video player

### ISSUE THREAD

**Issue by Enigmo96** [corso-android-ivan-morgillo/team-a#86]
`                    override fun onStateChange(youTubePlayer: YouTubePlayer, state: PlayerConstants.PlayerState) {
                    super.onStateChange(youTubePlayer, state)
                    val tracker = YouTubePlayerTracker()
                    youTubePlayer.addListener(tracker)
                    tracker.currentSecond
                    }`

**Comment by GaetanoCimino** [comment]
done
